style:
  NewLineAtEndOfFile:
    active: false
  ReturnCount:
    max: 4
  WildcardImport:
    active: false
  UnusedPrivateProperty:
    active: false
  MagicNumber:
    ignoreNumbers: ['-1', '0', '1', '2', '3', '4', '5', '6']

formatting:
  FinalNewline:
    active: false
  Indentation:
    active: false
  ImportOrdering:
    active: false
  Wrapping:
    active: false
  NoEmptyFirstLineInMethodBlock:
    active: false
  NoWildcardImports:
    active: false
  UnusedPrivateProperty:
    active: false

naming:
  VariableNaming:
    active: false
  ConstructorParameterNaming:
    active: false

performance:
  SpreadOperator:
    active: false

complexity:
  LongParameterList:
    ignoreDefaultParameters: true